name: 'Multi trigger cleanup'
runs:
  using: composite
  steps:
    - name: Report final status after workflow_run trigger
      if: ${{
          always()
          && github.event_name == 'workflow_run'
        }}
      uses: myrotvorets/set-commit-status-action@v2.0.1
      with:
        sha: ${{ github.event.workflow_run.head_sha }}
        status: ${{ job.status }}