name: 'Multi trigger cleanup'
runs:
  using: 'composite'
  steps:
    - name: Report final status after workflow_run trigger
      if: ${{
          github.event_name == 'workflow_run'
          || github.event_name == 'workflow_dispatch'
        }}
      uses: myrotvorets/set-commit-status-action@v2.0.1
      with:
        sha: |
          ${{ 
            github.event.workflow_run.head_sha
            || github.sha
          }}
        status: ${{ job.status }}