name: test

on:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows: [contributor_check]
    types:
      - completed

jobs:
  check-failed-trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: haya14busa/action-workflow_run-status@v1
      - run: echo "Skipped tests due to failed trigger"; exit 1
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: haya14busa/action-workflow_run-status@v1
      - name: Checkout triggering commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Check README content
        run: cat README.md
