name: test

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - contributor_check
    types:
      - completed

jobs:
  check-failed-trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    permissions:
      contents: read
      statuses: write
    steps:
      - run: echo "Skipped tests due to failed trigger"; exit 1
      - uses: myrotvorets/set-commit-status-action@v2.0.1
        if: always()
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          status: ${{ job.status }}
  test:
    runs-on: ubuntu-latest
    if: |
      ${{ github.event.workflow_run.conclusion == 'success' }}
      || ${{ github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          status: pending
      - name: Checkout triggering commit
        uses: actions/checkout@v4
        with:
          # The workflow_run trigger operates on the head commit of the
          # default branch by default. Ensure we checkout the commit that
          # triggered this workflow in the first place.
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Check README content
        run: cat README.md
      - name: Check fake secret
        env:
          SECRET_KEY: ${{ secrets.NOT_A_REAL_SECRET_KEY }}
        run: if [[ "$SECRET_KEY" == "NOT_A_REAL_SECRET_VAL" ]]; then echo "t"; else echo "f"; fi
      - name: sleep
        run: sleep 30
      - uses: myrotvorets/set-commit-status-action@v2.0.1
        if: always()
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          status: ${{ job.status }}
