name: test

on:
  workflow_dispatch:
  push:
    branches: [main]
  workflow_run:
    workflows:
      - contributor_check
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Report initial status after workflow_run trigger
        if: ${{ github.event_name == 'workflow_run' }}
        uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          status: pending
      - name: Fail on triggering workflow failure
        if: ${{
            github.event_name == 'workflow_run'
            && github.event.workflow_run.conclusion != 'success'
          }}
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.workflow_run.conclusion }}
          echo "Skipped tests due to failed trigger"
          exit 1
      - name: Fail on change to workflow file on workflow_run trigger
        if: ${{ github.event_name == 'workflow_run' }}
        run: |
          default_branch="${{ github.event.repository.default_branch }}"
          git fetch origin "default_branch"
          workflow_file=$(echo ${{ github.workflow_ref }} | cut -d'/' -f3- | cut -d'@' -f1)
          if [[ -n $(git diff "$default_branch" -- "$workflow_file") ]]; then
            cat <<EOF
            This job was triggered by a workflow_run event, which uses the
            workflow file from the default branch of the repo. However,
            changes were detected to this workflow file within the branch
            being checked. Therefore, any signals that would be produced by
            this workflow may not include the changes on the new branch. 
            Failing this job to prevent false positive outcomes.

            In order to pass this job, an owner of this repo must manually
            invoke it from the github actions menu using the branch being
            checked. That uses the workflow_dispatch trigger, which will
            pick up the modified version of this workflow file.
            EOF
            exit 1;
          fi
      - name: Checkout triggering commit
        uses: actions/checkout@v4
        with:
          # The path to the sha of the commit we want to test will depend
          # on the trigger type.
          ref: |
            ${{
              github.event.workflow_run.head_sha
              || github.sha
            }}
      - name: SHA check
        run: |
          echo "${{
              github.event.workflow_run.head_sha
              || github.sha
            }}"
      - name: Check README content
        run: cat README.md
      - name: Check fake secret
        env:
          SECRET_KEY: ${{ secrets.NOT_A_REAL_SECRET_KEY }}
        run: if [[ "$SECRET_KEY" == "NOT_A_REAL_SECRET_VAL" ]]; then echo "t"; else echo "f"; fi
      - name: Report final status after workflow_run trigger
        if: ${{
            always()
            && github.event_name == 'workflow_run'
          }}
        uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          status: ${{ job.status }}
