name: test

on:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows: [contributor_check]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "passed"
