name: test

on:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows: [contributor_check]
    types:
      - completed

jobs:
  check-failed-trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    permissions:
      issues: write
    steps:
      - run: echo "Skipped tests due to failed trigger"; exit 1
      - uses: myrotvorets/set-commit-status-action@v2.0.1
        if: always()
        with:
          status: ${{ job.status }}
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      issues: write
    steps:
      - uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          status: pending
      - name: Checkout triggering commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Check README content
        run: cat README.md
      - uses: myrotvorets/set-commit-status-action@v2.0.1
        if: always()
        with:
          status: ${{ job.status }}
