name: test

on:
  workflow_dispatch:
  push:
    branches: [main]
  workflow_run:
    workflows:
      - contributor_check
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout triggering commit
        uses: actions/checkout@v4
        with:
          # The path to the sha of the commit we want to test will depend
          # on the trigger type.
          ref: |
            ${{
              github.event.workflow_run.head_sha ||
              github.event.pull_request.head.sha ||
              github.sha
            }}
      - uses: ./.github/actions/multi-trigger-setup
      - name: SHA check
        run: |
          echo "${{
              github.event.workflow_run.head_sha
              || github.sha
            }}"
      - name: Check README content
        run: cat README.md
      - name: Check fake secret
        env:
          SECRET_KEY: ${{ secrets.NOT_A_REAL_SECRET_KEY }}
        run: if [[ "$SECRET_KEY" == "NOT_A_REAL_SECRET_VAL" ]]; then echo "t"; else echo "f"; fi
      - uses: ./.github/actions/multi-trigger-cleanup
