name: test

on:
  workflow_dispatch:
  push:
    branches: [main]
  workflow_run:
    workflows:
      - contributor_check
    types:
      - completed

jobs:
  check-workflow-run-trigger-failed:
    runs-on: ubuntu-latest
    # If this was triggered by a completed workflow run, do not run the
    # tests if that workflow run failed
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    permissions:
      contents: read
      statuses: write
    steps:
      - run: echo "Skipped tests due to failed trigger"; exit 1
      - uses: myrotvorets/set-commit-status-action@v2.0.1
        if: ${{ always() }}
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          status: ${{ job.status }}
  test:
    runs-on: ubuntu-latest
    # If this was triggered by a completed workflow, only run tests if that
    # workflow was successful. Always run tests for other triggers.
    if: |
      ${{ github.event_name != 'workflow_run' }} ||
      ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: myrotvorets/set-commit-status-action@v2.0.1
        if: ${{ github.event_name == 'workflow_run' }}
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          status: pending
      - name: Checkout triggering commit
        uses: actions/checkout@v4
        with:
          # The path to the sha of the commit we want to test will depend
          # on the trigger type.
          ref: |
            ${{
              github.event.workflow_run.head_sha || 
              github.sha
            }}
      - name: SHA check
        run: |
          echo "${{
              github.event.workflow_run.head_sha || 
              github.sha
            }}"
      - name: Check README content
        run: cat README.md
      - name: Check fake secret
        env:
          SECRET_KEY: ${{ secrets.NOT_A_REAL_SECRET_KEY }}
        run: if [[ "$SECRET_KEY" == "NOT_A_REAL_SECRET_VAL" ]]; then echo "t"; else echo "f"; fi
      - uses: myrotvorets/set-commit-status-action@v2.0.1
        if: ${{ github.event_name == 'workflow_run' }}
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          status: ${{ job.status }}
