name: test

on:
  workflow_dispatch:
  push:
    branches: [main]
  workflow_run:
    workflows:
      - contributor_check
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Report initial status after workflow_run trigger
        if: ${{ github.event_name == 'workflow_run' }}
        uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          status: pending
      - name: Fail on triggering workflow failure
        if: ${{
          github.event_name == 'workflow_run'
          && github.event.workflow_run.conclusion != 'success'
        }}
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.workflow_run.conclusion }}
          echo "Skipped tests due to failed trigger"
          exit 1
      - name: Checkout triggering commit
        uses: actions/checkout@v4
        with:
          # The path to the sha of the commit we want to test will depend
          # on the trigger type.
          ref: |
            ${{
              github.event.workflow_run.head_sha
              || github.sha
            }}
      - name: SHA check
        run: |
          echo "${{
              github.event.workflow_run.head_sha
              || github.sha
            }}"
      - name: Check README content
        run: cat README.md
      - name: Check fake secret
        env:
          SECRET_KEY: ${{ secrets.NOT_A_REAL_SECRET_KEY }}
        run: if [[ "$SECRET_KEY" == "NOT_A_REAL_SECRET_VAL" ]]; then echo "t"; else echo "f"; fi
      - name: Report final status after workflow_run trigger
        if: ${{
          always()
          && github.event_name == 'workflow_run'
        }}
        uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          status: ${{ job.status }}
